# Generated by Django 5.2.5 on 2025-09-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('usage_mb', models.FloatField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
