# Generated by Django 5.2.5 on 2025-09-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MikrotikUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=32, null=True)),
                ('bytes_in', models.BigIntegerField(default=0)),
                ('bytes_out', models.BigIntegerField(default=0)),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('raw', models.JSONField(default=dict)),
                ('last_seen', models.DateTimeField()),
            ],
        ),
    ]
