# Generated by Django 5.2.5 on 2025-09-16 21:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_userusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userusage',
            name='uptime',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_bytes_used', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.mikrotikuser')),
            ],
        ),
    ]
