# Generated by Django 5.2.5 on 2025-09-17 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_userusage_uptime_dailyusage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userusage',
            old_name='timestamp',
            new_name='snapshot_time',
        ),
    ]
