# Generated by Django 5.2.5 on 2025-09-26 08:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_monthlyusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mikrotikuser',
            name='last_warned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mikrotikuser',
            name='quote_bytes',
            field=models.BigIntegerField(default=1073741824),
        ),
        migrations.CreateModel(
            name='Notofication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent', models.BooleanField(default=False)),
                ('type', models.CharField(default='email', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.mikrotikuser')),
            ],
        ),
        migrations.CreateModel(
            name='WarnedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warnes_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.mikrotikuser')),
            ],
        ),
    ]
