# Generated by Django 5.2.5 on 2025-09-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_mikrotikuser_last_warned_mikrotikuser_quote_bytes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mikrotikuser',
            name='quote_bytes',
            field=models.BigIntegerField(default=6000),
        ),
    ]
