# Generated by Django 5.2.5 on 2025-09-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_alter_mikrotikuser_quote_bytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mikrotikuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
