# Generated by Django 5.2.5 on 2025-09-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_mikrotikuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mikrotikuser',
            name='email',
            field=models.EmailField(default='thebestworld21@gmail.com', max_length=254),
        ),
    ]
