# Generated by Django 5.2.5 on 2025-09-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0012_alter_mikrotikuser_email'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dailyusage',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_user_date'),
        ),
    ]
