# Generated by Django 5.2.5 on 2025-10-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_dailyusage_unique_user_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userusage',
            name='mac_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
