# Generated by Django 5.2.5 on 2025-10-29 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_userusage_mac_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mikrotikuser',
            name='bytes_in',
        ),
        migrations.RemoveField(
            model_name='mikrotikuser',
            name='bytes_out',
        ),
        migrations.RemoveField(
            model_name='mikrotikuser',
            name='mac_address',
        ),
        migrations.RemoveField(
            model_name='mikrotikuser',
            name='total_bytes',
        ),
    ]
