# Generated by Django 5.2.5 on 2025-11-24 12:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0015_remove_mikrotikuser_bytes_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mikrotikuser',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
